DWAPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0
  max_vel_theta: 1.0
  min_vel_theta: 0.2

  acc_lim_x: 0.7
  acc_lim_theta: 1.5

  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.25

  sim_time: 2.0
  vx_samples: 10
  vtheta_samples: 20

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.05

  meter_scoring: true
  transform_tolerance: 0.5